export const GET_POSTS_DATA_START = 'GET_POSTS_DATA_START';
export const GET_POSTS_DATA_SUCCESS = 'GET_POSTS_DATA_SUCCESS';
export const GET_POSTS_DATA_ERROR = 'GET_POSTS_DATA_ERROR';

export const GET_DETAILS_START = 'GET_DETAILS_START';
export const GET_DETAILS_REQUEST = 'GET_DETAILS_REQUEST';
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS';
export const GET_DETAILS_FAILURE = 'GET_DETAILS_FAILURE';

export const CLEAR_EMPLOYEE_DETAILS = 'CLEAR_EMPLOYEE_DETAILS';